#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output Virtual-1 --mode 1920x1080 --primary


# Set wallpaper
hsetroot -cover ~/.config/wallpaper.png &
polybar &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         	2
bspc config window_gap          	10

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color 	"#ffffff"
bspc config presel_feedback_color	"#ffffff"
bspc config urgent_border_color 	"#dd2727"


bspc rule -a firefox desktop='^1'
