#!/bin/sh

    
case "$(echo "Shutdown\nRestart\nLock" | dmenu \
    -p "Power:" \
    -l 3)" in
        Shutdown) 
            exec loginctl poweroff
            ;;
        Restart) 
            exec loginctl reboot
            ;;
        Lock)
            exec betterlockscreen -l blur
            ;;
esac
