#!/bin/sh

case "$(echo "Shutdown\nRestart\nLock" | dmenu  -p "" -l 5)" in
        Shutdown) exec loginctl poweroff;;
        Restart) exec loginctl reboot;;
        Lock) exec betterlockscreen -l;;
esac
