#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected="$(cat <(echo ~/Documents/Projects/) <(echo ~/Documents/) <(fd --type directory . --max-depth 3 ~/Documents/University/) | while read -r p; do zoxide query -l -s "$p"; done | sort -rnk1 | fzf --no-sort --color=bg+:#1e1e2e,bg:-1,spinner:#f5e0dc,hl:#f38ba8 --color=fg:#ffffff,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 | awk '{for (i=2; i<=NF; i++) printf $i (i<NF ? OFS : ORS)}')"
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
